<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Users.aspx.cs" Inherits="WebApplication1.WebForm1" UnobtrusiveValidationMode="None" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style>
        table {
            border-collapse: collapse;
            border-spacing: 5px;
        }
        table.fullborder {
            border: 1px solid black;
            text-align: left;
            padding: 5px;
            border-spacing: 5px;
            border-collapse: collapse;
        }
        th, td {
            padding: 5px;
        }
        td img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
            vertical-align: middle;
        }

    </style>
    <asp:Literal ID="jsCode" runat="server"></asp:Literal>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <p>Logged in as <asp:Label ID="lblUsername" runat="server" Text="Username" />.
                &nbsp;[<asp:LinkButton ID="lnkLogout" runat="server" Text="Log out" onclick="lnkLogout_Click" />]
                &nbsp;[<asp:LinkButton ID="lnkToMain" runat="server" Text="Main" onclick="lnkToMain_Click" />]
                &nbsp;[<asp:LinkButton ID="lnkToManage" runat="server" Text="Computers" onclick="lnkToManage_Click" />]
                &nbsp;[<asp:LinkButton ID="lnkToLog" runat="server" Text="Log" OnClick="lnkToLog_Click"></asp:LinkButton>]
            </p>
            <p>&nbsp;</p>
            <table style="margin-left: 0; margin-right: auto; border: none;">
                <tr>
                    <td colspan="2"><b>Add / Edit a user:</b></td>
                </tr>
                <tr>
                    <td>Username:</td>
                    <td><asp:TextBox ID="txtNewUsername" runat="server" Text=""></asp:TextBox></td>
                </tr>
                <tr>
                    <td>Password:</td>
                    <td><asp:TextBox ID="txtNewPassword" TextMode="Password" runat="server" Text=""></asp:TextBox></td>
                </tr>
                <tr>
                    <td>Type:</td>
                    <td>
                        <asp:DropDownList ID="ddlNewIsAdmin" runat="server">
                            <asp:ListItem Text="Normal User" Value="0"></asp:ListItem>
                            <asp:ListItem Text="Administrator" Value="1"></asp:ListItem>
                        </asp:DropDownList>
                    </td>
                </tr>
                <tr>
                    <td><asp:Button ID="btnAddNewUser" runat="server" Text="Add / Edit" onclick="btnAddUser_Click" /></td>
                </tr>
            </table>
            <p>&nbsp;</p>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                CancelSelectOnNullParameter="false" 
                SelectCommand="SELECT username, admin FROM [dbo].[Users] ORDER BY username"
                DeleteCommand="DELETE FROM [dbo].[Users] where username=@username"
                >
                <DeleteParameters>
                    <asp:ControlParameter ControlID="ComputersGridView" Name="username" PropertyName="SelectedDataKey" />
                </DeleteParameters>
            </asp:SqlDataSource>
            <asp:GridView CssClass="fullborder" ID="ComputersGridView" runat="server"
                ShowHeaderWhenEmpty="true"
                DataSourceID="SqlDataSource1" DataKeyNames="username"
                AutoGenerateColumns="false"
                AutoGenerateEditButton="false"
                AutoGenerateDeleteButton="false">
                <Columns>
                    <asp:BoundField DataField="username" HeaderText="Username" />
                    <asp:BoundField DataField="admin" HeaderText="Is Admin" />
                    <asp:TemplateField ShowHeader="false">
                        <ItemTemplate>
                            <asp:Button ID="btnGridRowDelete" runat="server" CausesValidation="false" CommandName="Delete" Text="Delete"/>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
